// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxCeESRiX0-aojhO6S9oUJhRKfa5FJKKI',
    appId: '1:807515670953:web:d655b55852caa962695cb8',
    messagingSenderId: '807515670953',
    projectId: 'expensetrackerapp-82215',
    authDomain: 'expensetrackerapp-82215.firebaseapp.com',
    storageBucket: 'expensetrackerapp-82215.firebasestorage.app',
    measurementId: 'G-NSX1YKC231',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbAzqfsC93kI5Ro9WkkZcviQollKLkF8g',
    appId: '1:807515670953:android:1fe84dbe27717303695cb8',
    messagingSenderId: '807515670953',
    projectId: 'expensetrackerapp-82215',
    storageBucket: 'expensetrackerapp-82215.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIlEzfCAYBWxxWynsuNUFMnH31VhmQoW0',
    appId: '1:807515670953:ios:94b9b11cb92bb143695cb8',
    messagingSenderId: '807515670953',
    projectId: 'expensetrackerapp-82215',
    storageBucket: 'expensetrackerapp-82215.firebasestorage.app',
    iosBundleId: 'com.example.expenseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIlEzfCAYBWxxWynsuNUFMnH31VhmQoW0',
    appId: '1:807515670953:ios:94b9b11cb92bb143695cb8',
    messagingSenderId: '807515670953',
    projectId: 'expensetrackerapp-82215',
    storageBucket: 'expensetrackerapp-82215.firebasestorage.app',
    iosBundleId: 'com.example.expenseapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxCeESRiX0-aojhO6S9oUJhRKfa5FJKKI',
    appId: '1:807515670953:web:b4fd6ea321c69bb4695cb8',
    messagingSenderId: '807515670953',
    projectId: 'expensetrackerapp-82215',
    authDomain: 'expensetrackerapp-82215.firebaseapp.com',
    storageBucket: 'expensetrackerapp-82215.firebasestorage.app',
    measurementId: 'G-NTD9KF6FY1',
  );
}
